In [1]:
#train_test_split is now in model_selection.
import os,cv2
import numpy as np 
import matplotlib.pyplot as plt

from sklearn.utils import shuffle 
from sklearn.model_selection import train_test_split 
 
from keras import backend as K 
K.set_image_dim_ordering('th') 
 
from keras.utils import np_utils 
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten 
from keras.layers.convolutional import Convolution2D, MaxPooling2D 
from keras.optimizers import SGD,RMSprop,Adam 
from sklearn.model_selection import StratifiedKFold 

Using TensorFlow backend.


In [2]:
img_rows=300 
img_cols=300 
num_channel=1 
num_epoch=30 
 
# Define the number of classes 
num_classes = 8 

In [3]:
Path = os.getcwd()
#num_classes = 8
dataset_path = "C:/Users/TA-D3TI-06 2018/Documents/Python Scripts/Dataset Ulos"
data = os.listdir(dataset_path)
img_data_list=[] 

for folder_dataset in data:
#     img_list = os.listdir(dataset_path+"/"+folder_dataset)
    img_list=os.listdir(dataset_path+"/"+ folder_dataset)  
    print ('Loaded the images of dataset-'+'{}\n'.format(folder_dataset))  
    for img in img_list:
        input_img=cv2.imread(dataset_path + "/"  + folder_dataset + "/" + img)
        input_img=cv2.cvtColor(input_img, cv2.COLOR_BGR2GRAY)
        input_img_resize=cv2.resize(input_img,(img_rows,img_cols))   
        img_data_list.append(input_img_resize) 
 
img_data = np.array(img_data_list) 
img_data = img_data.astype('float32') 
img_data /= 255
print (img_data.shape) 

Loaded the images of dataset-Ulos Bintang Maratur

Loaded the images of dataset-Ulos Harungguan

Loaded the images of dataset-Ulos Mangiring

Loaded the images of dataset-Ulos Ragi Hidup

Loaded the images of dataset-Ulos Ragi Hotang

Loaded the images of dataset-Ulos Sadum

Loaded the images of dataset-Ulos Sibolang

Loaded the images of dataset-Ulos Sitolutuho

(604, 300, 300)


In [4]:
print(input_img)

[[23 22 22 ... 11 10  9]
 [21 21 20 ... 10 10 10]
 [21 21 20 ... 13 13 12]
 ...
 [10 10 10 ...  6  6  5]
 [10 11 12 ...  7  6  6]
 [ 9  9 10 ...  7  7  7]]


In [5]:
if num_channel==1:  
    if K.image_dim_ordering()=='th':   
        img_data= np.expand_dims(img_data, axis=1)    
        print (img_data.shape)  
    else:   
        img_data= np.expand_dims(img_data, axis=4)    
        print (img_data.shape)    
else:  
    if K.image_dim_ordering()=='th':   
        img_data=np.rollaxis(img_data,3,1)   
        print (img_data.shape)    
        
# Assigning Labels 

num_of_samples = img_data.shape[0]
labels = np.ones((num_of_samples,),dtype='int64')

# =============================================================================
# names = ['Ulos Sibolang', 'Ulos Sadum', 'Ulos Ragi Hidup','Ulos Mangiring',
#'Ulos Harungguan', 'Ulos Ragi Hotang', 'Ulos Bintang Maratur', 'Ulos Sitolutuho']
# labels[0:632]=0
# labels[632:1440]=1
# labels[1440:2248]=2
# labels[2248:2912]=3
# labels[2912:3176]=4
# labels[3176:4272]=5
# labels[4272:4888]=6
# labels[4888:]=7
# # convert class labels to on-hot encoding
# =============================================================================

names = ['Ulos Bintang Maratur', 'Ulos Ragi Hidup', 'Ulos Sitolutuho','Ulos Sibolang', 
         'Ulos Ragi Hotang', 'Ulos Sadum', 'Ulos Harungguan', 'Ulos Mangiring']
labels[0:74]=0
labels[75:149]=1
labels[150:214]=2
labels[215:303]=3
labels[304:378]=4
labels[379:453]=5
labels[454:528]=6
labels[529:603]=7

Y = np_utils.to_categorical(labels, num_classes) 
#X = img_data
 
# #Shuffle the dataset 
x,y = shuffle(img_data,Y, random_state=2) 
seed = 7 
np.random.seed(seed) 
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed) 
 
#from sklearn.model_selection import train_test_split
#X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, train_size = 0.80, test_size = 0.20, random_state = 0)
#input_shape=img_data[0].shape 
#input_shape
#input_shape = input_shape + (1,)
#input_shape
#X_train = np.asarray( x[train_index]).reshape((len(X_train),360,380,1))
#X_Test = np.asarray(X_Test).reshape((len(X_Test),900,900,1))
#X_Train.shape
input_shape = img_data[0].shape
counter = 0 

for train_index, test_index in kfold.split(x,y[:,0]):      
    print("TRAIN:", train_index, "\nTEST:", test_index)      
    X_train, X_test = x[train_index], x[test_index]      
    y_train, y_test = y[train_index], y[test_index]      
    counter+=1
    nilai_learning_rate=0.001
    opt=Adam(lr=nilai_learning_rate)
    np.savetxt('C:/Users/TA-D3TI-06 2018/Documents/Python Scripts/output original/'+str(counter)+'-train_index.csv', train_index, fmt='%d', delimiter=',')
    np.savetxt('C:/Users/TA-D3TI-06 2018/Documents/Python Scripts/output original/'+str(counter)+'-test_index.csv', test_index, fmt='%d', delimiter=',')


(604, 1, 300, 300)
TRAIN: [  0   1   2   4   5   6   7   8   9  10  11  12  13  14  16  17  19  20
  21  22  23  24  25  27  29  30  31  32  33  34  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53  54  55  58  59  60  61
  62  63  65  66  67  68  69  70  71  72  73  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 102 103 104 105 106 107 108 109 110 111 112 113 115 116 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 135 136 137 138 139 140
 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158
 160 162 163 164 165 167 168 170 171 172 173 174 175 176 177 178 181 182
 183 184 185 186 188 190 191 192 193 194 195 197 198 199 200 201 202 203
 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 221 222
 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240
 241 242 243 244 246 247 248 249 250 251 252 253 254 257 258 259 260 261
 262 263 264 265 266 267 

In [6]:
def createModel():
    
    model = Sequential()
             
    model.add(Convolution2D(32, 3, strides=(3, 3), padding='same',input_shape=input_shape))
                 
    model.add(Activation('relu'))
                 
    model.add(Convolution2D(64, 3, strides=(3, 3)))
                 
    model.add(Activation('relu'))
                 
    model.add(MaxPooling2D(pool_size=(1, 1)))
                 
    model.add(Dropout(0.5))
                 
    model.add(Convolution2D(128, 3, strides=(3, 3)))
                 
    model.add(Activation('relu'))
                 
    model.add(Convolution2D(256, 3, strides=(3, 3)))
                 
    model.add(Activation('relu'))
                 
    model.add(MaxPooling2D(pool_size=(2, 2)))
                 
    model.add(Dropout(0.5))
                 
    model.add(Flatten())
                 
    model.add(Dense(128))
                 
    model.add(Activation('relu'))
    
    model.add(Dense(128))
                 
    model.add(Activation('relu'))
    
    model.add(Dense(128))
                 
    model.add(Activation('relu'))
                 
    model.add(Dense(num_classes))
                 
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=["accuracy"])    
    hist = model.fit(X_train, y_train, epochs=num_epoch, batch_size=16, validation_data=(X_test, y_test), verbose=1)
    global X_train, y_train, X_test, y_test
    score = model.evaluate(X_test, y_test, batch_size= 32, verbose=0)
    model.save('C:/Users/TA-D3TI-06 2018/Documents/Python Scripts/output original/'+str(counter)+'-K-fold-model.hdf5')
    print('K-Fold -', counter)    
    print('==================================')
    print('Test Loss:', score[0])
    print('Test accuracy:', score[1])
    print('==================================')
    X_train = []
    X_test = []
    y_train = []
    y_test = []

<>:48: SyntaxWarning: name 'X_train' is used prior to global declaration
<>:48: SyntaxWarning: name 'y_train' is used prior to global declaration
<>:48: SyntaxWarning: name 'X_test' is used prior to global declaration
<>:48: SyntaxWarning: name 'y_test' is used prior to global declaration
<>:48: SyntaxWarning: name 'X_train' is used prior to global declaration
<>:48: SyntaxWarning: name 'y_train' is used prior to global declaration
<>:48: SyntaxWarning: name 'X_test' is used prior to global declaration
<>:48: SyntaxWarning: name 'y_test' is used prior to global declaration
<>:48: SyntaxWarning: name 'X_train' is used prior to global declaration
<>:48: SyntaxWarning: name 'y_train' is used prior to global declaration
<>:48: SyntaxWarning: name 'X_test' is used prior to global declaration
<>:48: SyntaxWarning: name 'y_test' is used prior to global declaration
<ipython-input-6-fd480407b8d3>:48: SyntaxWarning: name 'X_train' is used prior to global declaration
  global X_train, y_train, X_

In [7]:
createModel()

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train on 544 samples, validate on 60 samples
Epoch 1/30
544/544 [==============================] - 6s 11ms/step - loss: 2.0745 - acc: 0.1195 - val_loss: 2.0796 - val_acc: 0.1167
Epoch 2/30
544/544 [==============================] - 6s 11ms/step - loss: 2.0776 - acc: 0.1250 - val_loss: 2.0762 - val_acc: 0.1500
Epoch 3/30
544/544 [==============================] - 6s 11ms/step - loss: 2.0631 - acc: 0.1581 - val_loss: 2.0784 - val_acc: 0.1500
Epoch 4/30
544/544 [==============================] - 6s 11ms/step - loss: 2.0673 - acc: 0.1599 - val_loss: 2.0702 - val_acc: 0.1167
Epoch 5/30
544/544 [==============================] - 6s 11ms/step - loss: 2.0182 - acc: 0.2371 - val_loss: 1.8820 - val_acc: 0.3167
Epoch 6/30
544/544 [==============================] - 6s 11ms/step - loss: 1.8708 - acc: 0.2518 - val_loss: 1.6341 - val_acc: 0

In [8]:
print(model.summary())

NameError: name 'model' is not defined